### ISSUE TITLE
Unable to create directory

### ISSUE THREAD

**Issue by raptoravis** [morganbengtsson/mos-skeleton#1]
## system

win10
vs2017 professional

```
# after git clone recursively
cd mos-skeleton
mkdir build
cd build
cmake .. -G "Visual Studio 15 2017 Win64"
```

then, open build/mos_skeleton.sln and build with the following errors:

---
error MSB3191: Unable to create directory "E:\developer\mos-skeleton\build\Debug\". Cannot create "E:\developer\mos-skeleton\build\Debug" because a file or directory with the same name already exists.

**Comment by morganbengtsson** [comment]
Thanks for reporting, should work better now but you never know with CMake.
